# Generated by Django 4.2.3 on 2023-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bid_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
